# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bilimselHesapMakinesiDesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget)
        self.zeroButton.setGeometry(QtCore.QRect(650, 680, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zeroButton.setFont(font)
        self.zeroButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.zeroButton.setObjectName("zeroButton")
        self.karekokButton = QtWidgets.QPushButton(self.centralwidget)
        self.karekokButton.setGeometry(QtCore.QRect(470, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.karekokButton.setFont(font)
        self.karekokButton.setObjectName("karekokButton")
        self.cscButton = QtWidgets.QPushButton(self.centralwidget)
        self.cscButton.setGeometry(QtCore.QRect(110, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cscButton.setFont(font)
        self.cscButton.setObjectName("cscButton")
        self.cosButton = QtWidgets.QPushButton(self.centralwidget)
        self.cosButton.setGeometry(QtCore.QRect(290, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cosButton.setFont(font)
        self.cosButton.setObjectName("cosButton")
        self.cosh1Button = QtWidgets.QPushButton(self.centralwidget)
        self.cosh1Button.setGeometry(QtCore.QRect(290, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cosh1Button.setFont(font)
        self.cosh1Button.setObjectName("cosh1Button")
        self.faktoriyelButton = QtWidgets.QPushButton(self.centralwidget)
        self.faktoriyelButton.setGeometry(QtCore.QRect(740, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.faktoriyelButton.setFont(font)
        self.faktoriyelButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.faktoriyelButton.setObjectName("faktoriyelButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget)
        self.nineButton.setGeometry(QtCore.QRect(740, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nineButton.setFont(font)
        self.nineButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.nineButton.setObjectName("nineButton")
        self.usAlmaButton = QtWidgets.QPushButton(self.centralwidget)
        self.usAlmaButton.setGeometry(QtCore.QRect(470, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.usAlmaButton.setFont(font)
        self.usAlmaButton.setObjectName("usAlmaButton")
        self.lgammaButton = QtWidgets.QPushButton(self.centralwidget)
        self.lgammaButton.setGeometry(QtCore.QRect(290, 680, 82, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lgammaButton.setFont(font)
        self.lgammaButton.setObjectName("lgammaButton")
        self.cothButton = QtWidgets.QPushButton(self.centralwidget)
        self.cothButton.setGeometry(QtCore.QRect(200, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cothButton.setFont(font)
        self.cothButton.setObjectName("cothButton")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget)
        self.percentButton.setGeometry(QtCore.QRect(470, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(True)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.expButton = QtWidgets.QPushButton(self.centralwidget)
        self.expButton.setGeometry(QtCore.QRect(830, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.expButton.setFont(font)
        self.expButton.setObjectName("expButton")
        self.secButton = QtWidgets.QPushButton(self.centralwidget)
        self.secButton.setGeometry(QtCore.QRect(200, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.secButton.setFont(font)
        self.secButton.setObjectName("secButton")
        self.cos1Button = QtWidgets.QPushButton(self.centralwidget)
        self.cos1Button.setGeometry(QtCore.QRect(290, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cos1Button.setFont(font)
        self.cos1Button.setObjectName("cos1Button")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget)
        self.oneButton.setGeometry(QtCore.QRect(560, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.oneButton.setFont(font)
        self.oneButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.oneButton.setObjectName("oneButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget)
        self.cButton.setGeometry(QtCore.QRect(790, 200, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.tan1Button = QtWidgets.QPushButton(self.centralwidget)
        self.tan1Button.setGeometry(QtCore.QRect(110, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tan1Button.setFont(font)
        self.tan1Button.setObjectName("tan1Button")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget)
        self.equalButton.setGeometry(QtCore.QRect(830, 680, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equalButton.setFont(font)
        self.equalButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.equalButton.setObjectName("equalButton")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(110, 50, 801, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setLineWidth(3)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.ikiPiButton = QtWidgets.QPushButton(self.centralwidget)
        self.ikiPiButton.setGeometry(QtCore.QRect(560, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ikiPiButton.setFont(font)
        self.ikiPiButton.setObjectName("ikiPiButton")
        self.coshButton = QtWidgets.QPushButton(self.centralwidget)
        self.coshButton.setGeometry(QtCore.QRect(290, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.coshButton.setFont(font)
        self.coshButton.setObjectName("coshButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget)
        self.fourButton.setGeometry(QtCore.QRect(560, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fourButton.setFont(font)
        self.fourButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.fourButton.setObjectName("fourButton")
        self.sin1Button = QtWidgets.QPushButton(self.centralwidget)
        self.sin1Button.setGeometry(QtCore.QRect(380, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sin1Button.setFont(font)
        self.sin1Button.setObjectName("sin1Button")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton.setGeometry(QtCore.QRect(830, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.minusButton.setFont(font)
        self.minusButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.minusButton.setObjectName("minusButton")
        self.ceButton = QtWidgets.QPushButton(self.centralwidget)
        self.ceButton.setGeometry(QtCore.QRect(650, 200, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ceButton.setFont(font)
        self.ceButton.setObjectName("ceButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget)
        self.sixButton.setGeometry(QtCore.QRect(740, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sixButton.setFont(font)
        self.sixButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.sixButton.setObjectName("sixButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.fiveButton.setGeometry(QtCore.QRect(650, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fiveButton.setFont(font)
        self.fiveButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.fiveButton.setObjectName("fiveButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget)
        self.eightButton.setGeometry(QtCore.QRect(650, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eightButton.setFont(font)
        self.eightButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.eightButton.setObjectName("eightButton")
        self.plusMinusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusMinusButton.setGeometry(QtCore.QRect(560, 680, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plusMinusButton.setFont(font)
        self.plusMinusButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.plusMinusButton.setObjectName("plusMinusButton")
        self.log1pButton = QtWidgets.QPushButton(self.centralwidget)
        self.log1pButton.setGeometry(QtCore.QRect(380, 680, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.log1pButton.setFont(font)
        self.log1pButton.setObjectName("log1pButton")
        self.cot1Button = QtWidgets.QPushButton(self.centralwidget)
        self.cot1Button.setGeometry(QtCore.QRect(200, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cot1Button.setFont(font)
        self.cot1Button.setObjectName("cot1Button")
        self.eulerButton = QtWidgets.QPushButton(self.centralwidget)
        self.eulerButton.setGeometry(QtCore.QRect(650, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eulerButton.setFont(font)
        self.eulerButton.setObjectName("eulerButton")
        self.cschButton = QtWidgets.QPushButton(self.centralwidget)
        self.cschButton.setGeometry(QtCore.QRect(380, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cschButton.setFont(font)
        self.cschButton.setObjectName("cschButton")
        self.kapaParantezButton = QtWidgets.QPushButton(self.centralwidget)
        self.kapaParantezButton.setGeometry(QtCore.QRect(650, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.kapaParantezButton.setFont(font)
        self.kapaParantezButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.kapaParantezButton.setObjectName("kapaParantezButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget)
        self.multiplyButton.setGeometry(QtCore.QRect(830, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.multiplyButton.setObjectName("multiplyButton")
        self.cotButton = QtWidgets.QPushButton(self.centralwidget)
        self.cotButton.setGeometry(QtCore.QRect(200, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cotButton.setFont(font)
        self.cotButton.setObjectName("cotButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget)
        self.twoButton.setGeometry(QtCore.QRect(650, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.twoButton.setFont(font)
        self.twoButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.twoButton.setObjectName("twoButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton.setGeometry(QtCore.QRect(830, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plusButton.setFont(font)
        self.plusButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.plusButton.setObjectName("plusButton")
        self.lnButton = QtWidgets.QPushButton(self.centralwidget)
        self.lnButton.setGeometry(QtCore.QRect(470, 680, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lnButton.setFont(font)
        self.lnButton.setObjectName("lnButton")
        self.sinhButton = QtWidgets.QPushButton(self.centralwidget)
        self.sinhButton.setGeometry(QtCore.QRect(380, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sinhButton.setFont(font)
        self.sinhButton.setObjectName("sinhButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget)
        self.sevenButton.setGeometry(QtCore.QRect(560, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sevenButton.setFont(font)
        self.sevenButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.sevenButton.setObjectName("sevenButton")
        self.sech1Button = QtWidgets.QPushButton(self.centralwidget)
        self.sech1Button.setGeometry(QtCore.QRect(200, 680, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sech1Button.setFont(font)
        self.sech1Button.setObjectName("sech1Button")
        self.mutlakXButton = QtWidgets.QPushButton(self.centralwidget)
        self.mutlakXButton.setGeometry(QtCore.QRect(740, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.mutlakXButton.setFont(font)
        self.mutlakXButton.setObjectName("mutlakXButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget)
        self.threeButton.setGeometry(QtCore.QRect(740, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.threeButton.setFont(font)
        self.threeButton.setStyleSheet("background-color: rgb(233, 151, 255);")
        self.threeButton.setObjectName("threeButton")
        self.sechButton = QtWidgets.QPushButton(self.centralwidget)
        self.sechButton.setGeometry(QtCore.QRect(290, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sechButton.setFont(font)
        self.sechButton.setObjectName("sechButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget)
        self.decimalButton.setGeometry(QtCore.QRect(740, 680, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.decimalButton.setFont(font)
        self.decimalButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.decimalButton.setObjectName("decimalButton")
        self.logButton = QtWidgets.QPushButton(self.centralwidget)
        self.logButton.setGeometry(QtCore.QRect(470, 600, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.logButton.setFont(font)
        self.logButton.setObjectName("logButton")
        self.tanhButton = QtWidgets.QPushButton(self.centralwidget)
        self.tanhButton.setGeometry(QtCore.QRect(110, 440, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tanhButton.setFont(font)
        self.tanhButton.setObjectName("tanhButton")
        self.piButton = QtWidgets.QPushButton(self.centralwidget)
        self.piButton.setGeometry(QtCore.QRect(470, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.piButton.setFont(font)
        self.piButton.setObjectName("piButton")
        self.csch1Button = QtWidgets.QPushButton(self.centralwidget)
        self.csch1Button.setGeometry(QtCore.QRect(110, 680, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.csch1Button.setFont(font)
        self.csch1Button.setObjectName("csch1Button")
        self.tanh1Button = QtWidgets.QPushButton(self.centralwidget)
        self.tanh1Button.setGeometry(QtCore.QRect(110, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tanh1Button.setFont(font)
        self.tanh1Button.setObjectName("tanh1Button")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget)
        self.divideButton.setGeometry(QtCore.QRect(830, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.divideButton.setFont(font)
        self.divideButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.divideButton.setObjectName("divideButton")
        self.acParantezButton = QtWidgets.QPushButton(self.centralwidget)
        self.acParantezButton.setGeometry(QtCore.QRect(560, 360, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.acParantezButton.setFont(font)
        self.acParantezButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 85, 0);\n"
"}")
        self.acParantezButton.setObjectName("acParantezButton")
        self.coth1Button = QtWidgets.QPushButton(self.centralwidget)
        self.coth1Button.setGeometry(QtCore.QRect(200, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.coth1Button.setFont(font)
        self.coth1Button.setObjectName("coth1Button")
        self.sinh1Button = QtWidgets.QPushButton(self.centralwidget)
        self.sinh1Button.setGeometry(QtCore.QRect(380, 520, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sinh1Button.setFont(font)
        self.sinh1Button.setObjectName("sinh1Button")
        self.tanButton = QtWidgets.QPushButton(self.centralwidget)
        self.tanButton.setGeometry(QtCore.QRect(110, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tanButton.setFont(font)
        self.tanButton.setObjectName("tanButton")
        self.sinButton = QtWidgets.QPushButton(self.centralwidget)
        self.sinButton.setGeometry(QtCore.QRect(380, 280, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sinButton.setFont(font)
        self.sinButton.setObjectName("sinButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bilimsel Hesap Makinesi"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.karekokButton.setText(_translate("MainWindow", "√"))
        self.cscButton.setText(_translate("MainWindow", "csc"))
        self.cosButton.setText(_translate("MainWindow", "cos"))
        self.cosh1Button.setText(_translate("MainWindow", "cosh⁻¹"))
        self.faktoriyelButton.setText(_translate("MainWindow", "n!"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.usAlmaButton.setText(_translate("MainWindow", "x² "))
        self.lgammaButton.setText(_translate("MainWindow", "lgamma"))
        self.cothButton.setText(_translate("MainWindow", "coth"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.expButton.setText(_translate("MainWindow", "exp"))
        self.secButton.setText(_translate("MainWindow", "sec"))
        self.cos1Button.setText(_translate("MainWindow", "cos⁻¹"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.tan1Button.setText(_translate("MainWindow", "tan⁻¹"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.ikiPiButton.setText(_translate("MainWindow", "2π"))
        self.coshButton.setText(_translate("MainWindow", "cosh"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.sin1Button.setText(_translate("MainWindow", "sin⁻¹"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.ceButton.setText(_translate("MainWindow", "CE"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.plusMinusButton.setText(_translate("MainWindow", "+/-"))
        self.log1pButton.setText(_translate("MainWindow", "log1p"))
        self.cot1Button.setText(_translate("MainWindow", "cot⁻¹"))
        self.eulerButton.setText(_translate("MainWindow", "e"))
        self.cschButton.setText(_translate("MainWindow", "csch"))
        self.kapaParantezButton.setText(_translate("MainWindow", ")"))
        self.multiplyButton.setText(_translate("MainWindow", "*"))
        self.cotButton.setText(_translate("MainWindow", "cot"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.lnButton.setText(_translate("MainWindow", "ln"))
        self.sinhButton.setText(_translate("MainWindow", "sinh"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.sech1Button.setText(_translate("MainWindow", "sech⁻¹"))
        self.mutlakXButton.setText(_translate("MainWindow", "|x|"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.sechButton.setText(_translate("MainWindow", "sech"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.logButton.setText(_translate("MainWindow", "log"))
        self.tanhButton.setText(_translate("MainWindow", "tanh"))
        self.piButton.setText(_translate("MainWindow", "π"))
        self.csch1Button.setText(_translate("MainWindow", "csch⁻¹"))
        self.tanh1Button.setText(_translate("MainWindow", "tanh⁻¹"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.acParantezButton.setText(_translate("MainWindow", "("))
        self.coth1Button.setText(_translate("MainWindow", "coth⁻¹"))
        self.sinh1Button.setText(_translate("MainWindow", "sinh⁻¹"))
        self.tanButton.setText(_translate("MainWindow", "tan"))
        self.sinButton.setText(_translate("MainWindow", "sin"))

