# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'standardHesapMakinesiDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(396, 643)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget)
        self.fourButton.setGeometry(QtCore.QRect(0, 345, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.fourButton.setFont(font)
        self.fourButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.fourButton.setObjectName("fourButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget)
        self.oneButton.setGeometry(QtCore.QRect(0, 445, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.oneButton.setFont(font)
        self.oneButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.oneButton.setObjectName("oneButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget)
        self.cButton.setGeometry(QtCore.QRect(200, 145, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.cButton.setFont(font)
        self.cButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.cButton.setObjectName("cButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget)
        self.nineButton.setGeometry(QtCore.QRect(200, 245, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.nineButton.setFont(font)
        self.nineButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.nineButton.setObjectName("nineButton")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(0, 0, 398, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setStyleSheet("border-color: rgb(64, 64, 255);")
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setLineWidth(3)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget)
        self.decimalButton.setGeometry(QtCore.QRect(0, 545, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.decimalButton.setFont(font)
        self.decimalButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.decimalButton.setObjectName("decimalButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget)
        self.divideButton.setGeometry(QtCore.QRect(300, 545, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.divideButton.setFont(font)
        self.divideButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.divideButton.setObjectName("divideButton")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget)
        self.percentButton.setGeometry(QtCore.QRect(0, 145, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.percentButton.setFont(font)
        self.percentButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.percentButton.setObjectName("percentButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget)
        self.equalButton.setGeometry(QtCore.QRect(200, 545, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.equalButton.setFont(font)
        self.equalButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.equalButton.setObjectName("equalButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget)
        self.twoButton.setGeometry(QtCore.QRect(100, 445, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.twoButton.setFont(font)
        self.twoButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.twoButton.setObjectName("twoButton")
        self.plusMinusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusMinusButton.setGeometry(QtCore.QRect(100, 145, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.plusMinusButton.setFont(font)
        self.plusMinusButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.plusMinusButton.setObjectName("plusMinusButton")
        self.ceButton = QtWidgets.QPushButton(self.centralwidget)
        self.ceButton.setGeometry(QtCore.QRect(300, 145, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ceButton.setFont(font)
        self.ceButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.ceButton.setObjectName("ceButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton.setGeometry(QtCore.QRect(300, 345, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.minusButton.setFont(font)
        self.minusButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.minusButton.setObjectName("minusButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget)
        self.sixButton.setGeometry(QtCore.QRect(200, 345, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.sixButton.setFont(font)
        self.sixButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.sixButton.setObjectName("sixButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton.setGeometry(QtCore.QRect(300, 245, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.plusButton.setFont(font)
        self.plusButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.plusButton.setObjectName("plusButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget)
        self.multiplyButton.setGeometry(QtCore.QRect(300, 445, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.multiplyButton.setObjectName("multiplyButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.fiveButton.setGeometry(QtCore.QRect(100, 345, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.fiveButton.setFont(font)
        self.fiveButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.fiveButton.setObjectName("fiveButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget)
        self.sevenButton.setGeometry(QtCore.QRect(0, 245, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.sevenButton.setFont(font)
        self.sevenButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.sevenButton.setObjectName("sevenButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget)
        self.threeButton.setGeometry(QtCore.QRect(200, 445, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.threeButton.setFont(font)
        self.threeButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.threeButton.setObjectName("threeButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget)
        self.eightButton.setGeometry(QtCore.QRect(100, 245, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.eightButton.setFont(font)
        self.eightButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.eightButton.setObjectName("eightButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget)
        self.zeroButton.setGeometry(QtCore.QRect(100, 545, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.zeroButton.setFont(font)
        self.zeroButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.zeroButton.setObjectName("zeroButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Standard Hesap Makinesi"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.plusMinusButton.setText(_translate("MainWindow", "+/-"))
        self.ceButton.setText(_translate("MainWindow", "CE"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.multiplyButton.setText(_translate("MainWindow", "*"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
